# Generated by Django 6.0.5 on 2026-06-02 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Код ресурса')),
                ('name', models.CharField(max_length=150, verbose_name='Название ресурса')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Ресурс приложения',
                'verbose_name_plural': 'Ресурсы приложения',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название роли')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('password_hash', models.CharField(max_length=255, verbose_name='Хеш пароля')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='accounts.role', verbose_name='Роль')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(unique=True, verbose_name='Токен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='accounts.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Токен авторизации',
                'verbose_name_plural': 'Токены авторизации',
            },
        ),
        migrations.CreateModel(
            name='AccessRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_permission', models.BooleanField(default=False, verbose_name='Просмотр своих объектов')),
                ('read_all_permission', models.BooleanField(default=False, verbose_name='Просмотр всех объектов')),
                ('create_permission', models.BooleanField(default=False, verbose_name='Создание объектов')),
                ('update_permission', models.BooleanField(default=False, verbose_name='Изменение своих объектов')),
                ('update_all_permission', models.BooleanField(default=False, verbose_name='Изменение всех объектов')),
                ('delete_permission', models.BooleanField(default=False, verbose_name='Удаление своих объектов')),
                ('delete_all_permission', models.BooleanField(default=False, verbose_name='Удаление всех объектов')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_rules', to='accounts.businesselement', verbose_name='Ресурс')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_rules', to='accounts.role', verbose_name='Роль')),
            ],
            options={
                'verbose_name': 'Правило доступа',
                'verbose_name_plural': 'Правила доступа',
                'unique_together': {('role', 'element')},
            },
        ),
    ]
